#!/usr/bin/env python3
#
# Copyright VyOS maintainers and contributors <maintainers@vyos.io>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T3417: migrate IS-IS tagNode to node as we can only have one IS-IS process

from sys import argv
from sys import exit

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

base = ['protocols', 'isis']
config = ConfigTree(config_file)

if not config.exists(base):
    # Nothing to do
    exit(0)

if not config.is_tag(base):
    # Nothing to do
    exit(0)

# Get IS-IS domain ID
domain_id = config.list_nodes(base)
if domain_id:
    # We need a temporary copy of the config
    tmp_base = ['protocols', 'isis2']
    config.copy(base + domain_id, tmp_base)

# Now it's save to delete the old configuration
config.delete(base)

# Rename temporary copy to new final config (IS-IS domain key is static and no
# longer required to be set via CLI)
if config.exists(tmp_base):
    config.rename(tmp_base, 'isis')

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
