#!/usr/bin/env python3
#
# Copyright VyOS maintainers and contributors <maintainers@vyos.io>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# T7163: migrate "address-family ipv4|6-unicast redistribute table" from a multi
# leafNode to a tagNode. This is needed to support per table definition of a
# route-map and/or metric

from sys import argv
from sys import exit

from vyos.configtree import ConfigTree

if len(argv) < 2:
    print("Must specify file name!")
    exit(1)

file_name = argv[1]

with open(file_name, 'r') as f:
    config_file = f.read()

config = ConfigTree(config_file)

bgp_base = ['protocols', 'bgp']
if not config.exists(bgp_base):
    exit(0)

for address_family in ['ipv4-unicast', 'ipv6-unicast']:
    # there is no non-main routing table beeing redistributed under this addres family
    # bail out early and continue with next AFI
    table_path = bgp_base + ['address-family', address_family, 'redistribute', 'table']
    if not config.exists(table_path):
        continue

    tables = config.return_values(table_path)
    config.delete(table_path)

    for table in tables:
        config.set(table_path + [table])
        config.set_tag(table_path)

try:
    with open(file_name, 'w') as f:
        f.write(config.to_string())
except OSError as e:
    print(f'Failed to save the modified config: {e}')
    exit(1)
