---
name: Add pull request labels

on:
  pull_request_target:
    branches:
<<<<<<< HEAD
=======
      - current
      - circinus
>>>>>>> 43b2d3268 (T8100: updated pullrequest_target trigger branch filters updated)
      - sagitta

permissions:
  pull-requests: write
  contents: read

jobs:
  add-pr-label:
    uses: vyos/.github/.github/workflows/add-pr-labels.yml@sagitta
    secrets: inherit
